nights       : ['n1']
instrument   : 'OSIRIS'
output_dir      : '/u/mfreeman/work/PCU/script_testing/distortion_testing/outputs1/'
legendre_order : 5
generate_new_fp : True
generate_reference_frame : False
fp_iterations  : 4
ref_iterations : 8
centred         : True
use_flystar_velocity  : False
manually_average_star_positions : True

n1:
  target          : 'PCU'
  ref_instrument  : 'PCU'  #'PCU' or 'Hubble' 
  reference_file  : '/u/mfreeman/code/python/bdc/pinhole_grid_positions.txt' #'je0o61lzq_flt.xymrduvqpk'
  log_file        : '/u/mfreeman/work/PCU/script_testing/day3/PCU_20230413_060326.log'
  starlist_dir    : '/u/mfreeman/work/PCU/script_testing/day3/raw/'      #location of the starlists
  fits_dir        : '/u/mfreeman/work/PCU/script_testing/day3/raw/'      #location of the .fits files (or _flip.fits for OSIRIS)
  bad_files       : []
  tform_dir       : '/u/mfreeman/work/PCU/script_testing/day3/tforms1/'  #4-parameter transformation guesses will be loaded from and saved to here.
  mag_limits      : [-5,16]      #stars outside this magnitude range are discarded. Also passed as limits to mosaic_to_ref()
  mag_tolerance   : [3, 3, 3]
  # targetID        : 1745948323734090368   #gaia ID of target star. Ra and Dec used in prepare_gaia_for_flystar()
  target_RA        : 0         #RA of target. Reference coordinates are given in relative RA to this position.  
  target_DEC       : 0
  # radius        : 20   #arcseconds
  single_fit      : True  #run Mosaic2Ref for each image individually. Only works for true, delete?
  rad_tolerance   : [0.6, 0.5, 0.4]
  dont_trim       : [] #can probably delete this.
  slice           : [0,1]   #null
n2:
  target          : 'M92'
  nightDir        : '/u/mfreeman/work/d/n2/'
  cleanDir        : nightDir + 'clean/m15_kn3_tdOpen/'
  starfindDir     : cleanDir + 'starfinder/'
  stackDir        : cleanDir + 'stacks/'
  bad_files       : []
  mag_limits      : [6,16]
  mag_tolerance   : [2, 2, 2]
  reference_file  : '/g/lu/data/m92/hst_ref/NGC6341cp.pm' #'idk901xpq_flt.xymrduvqpk'
  targetID        : 1360405503461790848  #gaia ID of target star. Ra and Dec used in prepare_gaia_for_flystar()
  ra_field        : 259.285096306648     #approximate centre of FoV, selects gaia stars in radius
  dec_field       : 43.13751895071527
  # radius        : 20   #arcseconds
  minmag          : 15.4  #dimmest mag for cut
  rad_tolerance   : [0.4, 0.4, 0.2]
  single_fit      : True  #run Mosaic2Ref for each image individually
  dont_trim       : []


